# testing 的通用方法-总结

- **(1) 遇到断言错误，标识测试失败时**
  - **Fail : 测试失败，测试继续，也就是之后的代码依然会执行**
  - **FailNow : 测试失败，测试中断，内部调用 `runtime.Goexit()` 中断测试**
- **(2) 遇到断言错误，跳过错误，但不标识测试失败时**
  - **SkipNow : 跳过测试，测试中断，内部调用 `runtime.Goexit()` 中断测试**
- **(3) 遇到断言错误，只希望打印信息时**
  - **Log : 输出信息**
  - **Logf : 输出格式化的信息**
- **(4) 遇到断言错误，跳过测试，并且打印出信息时**
  - **Skip : 相当于 Log + SkipNow**
  - **Skipf : 相当于 Logf + SkipNow**
- **(5) 遇到断言错误，标识测试失败，并打印信息，但测试继续时**
  - **Error : 相当于 Log + Fail**
  - **Errorf : 相当于 Logf + Fail**
- **(6) 遇到断言错误，标识测试失败，打印信息，但中断测试时**
  - **Fatal : 相当于 Log + FailNow**
  - **Fatalf : 相当于 Logf + FailNow**

# testing 的通用方法

T 结构内部是继承自 common 结构，common 结构提供集中方法，是我们经常会用到的：

1）当我们遇到一个断言错误的时候，我们就会判断这个测试用例失败，就会使用到：

    Fail : case 失败，测试用例继续
    FailedNow : case 失败，测试用例中断

2）当我们遇到一个断言错误，只希望跳过这个错误，但是不希望标示测试用例失败，会使用到：

    SkipNow : case 跳过，测试用例不继续

3）当我们只希望在一个地方打印出信息，我们会用到 :

    Log : 输出信息
    Logf : 输出有 format 的信息

4）当我们希望跳过这个用例，并且打印出信息 :

    Skip : Log + SkipNow
    Skipf : Logf + SkipNow

5）当我们希望断言失败的时候，测试用例失败，打印出必要的信息，但是测试用例继续：

    Error : Log + Fail
    Errorf : Logf + Fail

6）当我们希望断言失败的时候，测试用例失败，打印出必要的信息，测试用例中断：

    Fatal : Log + FailNow
    Fatalf : Logf + FailNow
